version: "3.7"

services:
  savior:
    # network_mode: bridge
    image: savior
    build: ./
    network_mode: host
    environment:
      # GUNICORN
      - SAVIOR_PYTHON_PORT=5000

      # LOGS
      - NIVEL_LOGS=INFO
      - DIRECTORIO_LOGS=logs/

      # APP
      - POOL_SIZE_DEFAULT=50
      - MAX_OVERFLOW_DEFAULT=100
      - DIRECTORY_FILES=files/
      - SAVIOR_ENVIRONMENT_MODE=development
      - SAVIOR_MOCK=true
      - SAVIOR_DATABASE_NAME=savior_db
      - SAVIOR_ENTITY_DIR=app/repositories/entity/
      - SAVIOR_AUTOCREATE_DB=true

    restart: always
    volumes:
      - ./logs:/usr/src/logs
      - ./files:/usr/src/files
      
    # ports:
    #   - 5000:5000
